// 生成ファイル — 手で編集しない。
//
// 正典: apps/kotlin/androidApp/src/main/res/values/strings.xml
// 再生成: make ios-strings   （整合の検証: ./hack/check-ui-strings.sh）
//
// 文言を直すときは strings.xml だけを編集する。1 ファイルの編集が
// Android と iOS の両方に効く。

import Foundation

enum L {
    static let appName = "Runa"
    static let tabHome = "ホーム"
    static let tabTodaysSong = "きょうの一曲"
    static let tabDiary = "ダイアリー"
    static let tabGallery = "ギャラリー"
    static let tabSettings = "設定"
    static let healthOk = "接続OK"
    static let healthError = "接続エラー"
    static let placeholderComingSoon = "準備中"
    static let actionBack = "戻る"
    static let actionClose = "閉じる"
    static let galleryTitle = "ひかりの記録"
    static let galleryThemeMonotone = "モノトーン"
    static let galleryThemePink = "ピンク"
    static let galleryAdd = "写真を追加"
    static let galleryEmptyLine = "まだ、ひかりの記録はありません。"
    static let galleryEmptyBody = "最初のひかりを、\nそっと残してみませんか。"
    static let galleryClose = "閉じる"
    static let galleryDelete = "削除"
    static let brandName = "Runa"
    static let logoWordmark = "LUNA"
    static let splashTagline = "月あかりの記録"
    static let onboarding1Title = "あなたの夜に、\nそっと寄り添う。"
    static let onboarding2Title = "三つの、\n静かな時間。"
    static let onboardingHint = "すすむ"
    static let notifTitle = "夜のとばりに、\nそっとお知らせ。"
    static let notifBody = "やさしい時刻に、今日をふりかえる合図を。\n設定はあとからでも変えられます。"
    static let notifAllow = "許可する"
    static let actionSkip = "いまはしない"
    static let signinTagline = "あなたの夜を、はじめましょう。"
    static let signinApple = "Appleでつづける"
    static let signinGoogle = "Googleでつづける"
    static let signinEmailContinue = "メールでつづける"
    static let signinSkip = "いまはスキップ"
    static let signinEmailTitle = "メールではじめる"
    static let signinEmailLabel = "メールアドレス"
    static let signinPasswordLabel = "パスワード"
    static let signinNameLabel = "表示名（任意）"
    static let actionLogin = "ログイン"
    static let actionSignup = "新規登録"
    static let signinToggleToSignup = "アカウントをお持ちでない方はこちら"
    static let signinToggleToLogin = "すでにアカウントをお持ちの方はこちら"
    static let signinErrorGeneric = "サインインに失敗しました。"
    static let signinProviderUnconfigured = "この方法は、いまは選べません。"
    static let signinErrorAuth = "認証できませんでした。"
    static let signinErrorPrepare = "サインインの準備ができませんでした。"
    static func homeGreeting(_ a1: String) -> String {
        String(format: "こんばんは、%1$@さん", a1)
    }
    static let actionSignOut = "サインアウト"
    static let diaryListTitle = "日々の記録"
    static let diaryNew = "綴る"
    static let diaryEmptyTitle = "まだ、なにもない夜。"
    static let diaryEmptyBody = "最初のひとことを、\nそっと綴ってみませんか。"
    static let diaryEmptyCta = "綴りはじめる"
    static let diaryBannerSyncing = "同期しています…"
    static let diaryEditorPrompt = "きょう、心にのこったこと。"
    static let diaryEditorAutosave = "静かに、綴る"
    static let diaryEditorSaving = "保存しています…"
    static let diaryEditorSaved = "保存しました"
    static let diaryEditorError = "保存に、つまずきました"
    static let diaryClose = "とじる"
    static let diaryDetailBack = "記録"
    static let diaryActionEdit = "編集"
    static let diaryActionDelete = "削除"
    static let diaryDeleteConfirmTitle = "この記録を削除しますか？"
    static let diaryDeleteConfirmBody = "削除した記録は元に戻せません。"
    static let actionDelete = "削除する"
    static let actionCancel = "やめる"
    static let diaryOpenInsight = "うつろい"
    static let insightLetterTitle = "あなたへの、手紙"
    static let insightToggleWeek = "週"
    static let insightToggleMonth = "月"
    static let insightMoonNew = "新月"
    static let insightMoonFull = "満月"
    static func insightUnmooded(_ a1: Int) -> String {
        String(format: "しるしのない夜も、%1$ldつ。", a1)
    }
    static let insightEmptyTitle = "まだ、しるした夜がありません。"
    static let insightEmptyBody = "この期間は、静かなままです。"
    static let homeOfflineHint = "オフライン表示中（月あかりは端末で計算しています）"
    static let homeNoQuote = "今日の言葉は、まだ紡がれていません。"
    static let homeQuoteCaption = "きょうの、ひとこと"
    static let todaySongNone = "きょうの一曲は、まだ選ばれていません。"
    static let todaySongNoneBody = "選ばれた一曲は、ここに灯ります。"
    static let todaySongOpenArchive = "これまでの一曲"
    static let songArchiveTitle = "これまでの一曲"
    static let songArchiveHistory = "再生の記録"
    static let songArchiveEmpty = "アーカイブはまだありません。"
    static let songArchiveEmptyBody = "日々の一曲が、ここに積もっていきます。"
    static let songArchiveLoadMore = "もっと見る"
    static let playerPlay = "再生"
    static let playerPause = "一時停止"
    static let diaryOpenCalendar = "ふりかえり"
    static let calendarLegend = "記録のある日に、月あかり"
    static let calendarWriteOnDay = "この日を綴る"
    static let todaysMoonLabel = "今日の月"
    static func todaysMoonAge(_ a1: String, _ a2: String) -> String {
        String(format: "月齢 %1$@ ・ %2$@", a1, a2)
    }
    static func todaysMoonNext(_ a1: String, _ a2: String) -> String {
        String(format: "next ▸ %1$@　%2$@", a1, a2)
    }
    static let settingsTitle = "設定"
    static let settingsRowTheme = "テーマ"
    static let settingsRowNotifications = "通知"
    static let settingsRowPrivacyLock = "プライバシー・ロック"
    static let settingsRowAccount = "アカウント・データ"
    static let notifSettingsEyebrow = "NOTIFICATION"
    static let notifSettingsTitle = "夜のリマインダー"
    static let notifSettingsToggle = "リマインダーを受け取る"
    static let notifSettingsTimeCaption = "おやすみ前の、しずかな時刻"
    static let notifSettingsFooter = "その時刻に、月がそっと\n今日をふりかえるひとことを。"
    static let notifSettingsPickTime = "時刻を選ぶ"
    static let notifValueOff = "オフ"
    static let lockSettingsEyebrow = "PRIVACY"
    static let lockSettingsTitle = "ロック"
    static let lockSettingsCaption = "あなたの夜を、あなただけに。"
    static let lockSettingsToggle = "ロックする"
    static let lockSettingsUnavailable = "この端末では、生体認証や画面ロックが設定されていません。端末の設定をご確認ください。"
    static let lockValueOn = "オン"
    static let lockValueOff = "オフ"
    static let lockGateMessage = "あなたの夜は、\n守られています。"
    static let lockGateUnlock = "ひらく"
    static let lockGateAuthenticating = "確認しています…"
    static let lockGateFailed = "もう一度、お試しください。"
    static let timePickerConfirm = "決定"
    static let timePickerCancel = "やめる"
    static let settingsPremiumTitle = "LUNA +"
    static let settingsPremiumSubtitle = "プレミアムで、もっと深く"
    static func settingsVersion(_ a1: String) -> String {
        String(format: "LUNA version %1$@", a1)
    }
    static let themeEyebrow = "THEME"
    static let themeTitle = "テーマ"
    static let themeDarkName = "夜（ダーク）"
    static let themeDarkDesc = "深い夜色に、月あかり"
    static let themeLightName = "あさ（ライト）"
    static let themeLightDesc = "朝の光のような、白"
    static let themePinkName = "ピンク×ピンク"
    static let themePinkDesc = "ルナピンクの、灯り"
    static let themeFooter = "あなたの夜に、あわせて。"
    static let themeSelected = "選択中"
    static let accountEyebrow = "ACCOUNT"
    static let accountTitle = "アカウント・データ"
    static let accountEditName = "表示名を編集"
    static let accountNameLabel = "表示名"
    static let accountSave = "保存"
    static let accountExport = "エクスポート"
    static let accountExportJson = "JSONで書き出す"
    static let accountExportText = "テキストで書き出す"
    static let accountExportPreparing = "エクスポートを準備しています…"
    static let accountExportShareTitle = "データのエクスポート"
    static let accountDelete = "アカウントを削除"
    static let accountDeleteConfirmTitle = "アカウントを削除しますか？"
    static let accountDeleteConfirmBody = "日記・画像を含むすべてのデータが完全に削除され、元に戻せません。"
    static let accountDeleting = "削除しています…"
    static let accountLoadError = "プロフィールを取得できませんでした。"
    static let stateLoadingCaption = "月が、のぼるまで。"
    static let stateOfflineTitle = "雲が、月をかくしています。"
    static let stateOfflineBody = "接続がありません。\n綴った言葉は、端末に守られています。"
    static let stateOfflineCta = "もう一度ためす"
    static let stateErrorTitle = "すこし、つまずきました。"
    static let stateErrorBody = "うまく読み込めませんでした。\nゆっくり、もう一度。"
    static let stateErrorCta = "やりなおす"
    static let stateAuthTitle = "また、ここから。"
    static let stateAuthBody = "サインインの有効期限が切れました。"
    static let stateAuthCta = "サインインし直す"
    static let stateBannerOffline = "オフライン。記録は端末に守られています。"
    static let stateBannerError = "同期に、すこしつまずいています。"
}
